services:
  - type: web
    name: blackbitswan-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
